# Generated by Django 5.1.1 on 2024-09-10 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.FileField(upload_to='categories\\images')),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rate', models.IntegerField()),
                ('image', models.FileField(upload_to='products\\images')),
                ('color', models.CharField(default='', max_length=50)),
                ('care_instructions', models.TextField(default='')),
                ('design', models.CharField(default='', max_length=100)),
                ('fabric', models.CharField(default='', max_length=100)),
                ('pattern', models.CharField(default='', max_length=100)),
                ('country_of_origin', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.products')),
            ],
        ),
    ]
