# Generated by Django 5.1.1 on 2024-09-11 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_cart_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart_item',
            old_name='buy',
            new_name='cartprod',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
        migrations.AddField(
            model_name='cart_item',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.products'),
            preserve_default=False,
        ),
    ]
