# Generated by Django 5.1.1 on 2024-09-11 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_cart_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart_item',
        ),
    ]
