# Generated by Django 5.1.1 on 2024-09-27 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_products_design_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='price',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='quantity',
        ),
    ]
